In [1]:
import numpy as np
import scipy
import tensorly

lambda_ = np.asarray([39.288, 10.676])

U1 = np.asarray([.5719, .1469, .5885, .9817, .5715, -.1210,]).reshape(3, -1)

U2 = np.asarray([.5121, -.4042, .6284, .5877, .5856, .7009,]).reshape(3, -1)

U3 = np.asarray([.5605, -.3179, .4921, -.3682, .6661, .8737,]).reshape(3, -1)

U4 = np.asarray([.7502, -.9201, .6612, .3917,]).reshape(2, -1)


In [2]:
"""
P1.I.b.i
------
Compute lambda_1 * U_1,1 outer_product U_2,1 outer_product U_3,1 outer_product U_4,1.
"""
lambda_1 = lambda_[0]
u11 = U1[:,0]
u21 = U2[:,0]
u31 = U3[:,0]
u41 = U4[:,0]

Xi = np.zeros(u11.size * u21.size * u31.size * u41.size).reshape(
    (u11.size, u21.size, u31.size, u41.size)
    )

for aa in range(len(u11)):
    for bb in range(len(u21)):
        for cc in range(len(u31)):
            for dd in range(len(u41)):
                Xi[aa, bb, cc, dd] = \
                    u11[aa] * u21[bb] * u31[cc] * u41[dd]
                
# Multiply each element of Xi by lambda_1.
Xi*=lambda_1

# Print dimensionality and contents of resulting tensor. 
print("Dimensionality of Xi: {}".format(Xi.shape))

print("")
print("Xi_1,1")
print(Xi[:,:,0,0])

print("\nXi_1,2")
print(Xi[:,:,0,1])

print("\nXi_2,1")
print(Xi[:,:,1,0])

print("\nXi_2,2")
print(Xi[:,:,1,1])

print("\nXi_3,1")
print(Xi[:,:,2,0])

print("\nXi_3,2")
print(Xi[:,:,2,1])


Dimensionality of Xi: (3, 3, 3, 2)

Xi_1,1
[[4.83824 5.93702 5.53266]
 [4.97868 6.10935 5.69325]
 [4.83486 5.93287 5.52879]]

Xi_1,2
[[4.26426 5.23269 4.87629]
 [4.38803 5.38457 5.01783]
 [4.26127 5.22903 4.87288]]

Xi_2,1
[[4.24781 5.21251 4.85749]
 [4.37111 5.36381 4.99848]
 [4.24484 5.20886 4.85409]]

Xi_2,2
[[3.74387 4.59412 4.28122]
 [3.85254 4.72747 4.40548]
 [3.74125 4.59091 4.27822]]

Xi_3,1
[[5.74978 7.05558 6.57503]
 [5.91667 7.26038 6.76587]
 [5.74576 7.05064 6.57043]]

Xi_3,2
[[5.06766 6.21854 5.795  ]
 [5.21475 6.39904 5.9632 ]
 [5.06411 6.21419 5.79095]]


In [3]:
"""
P1.I.b.ii
-------
Compute lambda_2 * U_1,2 outer_product U_2,2 outer_product U_3,2 outer_product U_4,2.
"""
lambda_2 = lambda_[1]
u12 = U1[:,1]
u22 = U2[:,1]
u32 = U3[:,1]
u42 = U4[:,1]

Xii = np.zeros(u12.size * u22.size * u32.size * u42.size).reshape(
    (u12.size, u22.size, u32.size, u42.size)
    )

for aa in range(len(u12)):
    for bb in range(len(u22)):
        for cc in range(len(u32)):
            for dd in range(len(u42)):
                Xii[aa, bb, cc, dd] = \
                    u12[aa] * u22[bb] * u32[cc] * u42[dd]

# Multiply each element of Xii by lambda_2.
Xii*=lambda_2

# Print dimensionality and slices of resulting tensor. 
print("Dimensionality of Xii: {}".format(Xii.shape))

print("")
print("Xii_1,1")
print(Xii[:,:,0,0])

print("\nXii_1,2")
print(Xii[:,:,0,1])

print("\nXii_2,1")
print(Xii[:,:,1,0])

print("\nXii_2,2")
print(Xii[:,:,1,1])

print("\nXii_3,1")
print(Xii[:,:,2,0])

print("\nXii_3,2")
print(Xii[:,:,2,1])


Dimensionality of Xii: (3, 3, 3, 2)

Xii_1,1
[[-0.18542  0.26959  0.32152]
 [-1.23911  1.80164  2.14867]
 [ 0.15273 -0.22206 -0.26484]]

Xii_1,2
[[ 0.07894 -0.11477 -0.13688]
 [ 0.52751 -0.76699 -0.91472]
 [-0.06502  0.09454  0.11274]]

Xii_2,1
[[-0.21476  0.31225  0.3724 ]
 [-1.43517  2.08671  2.48864]
 [ 0.17689 -0.2572  -0.30674]]

Xii_2,2
[[ 0.09142 -0.13293 -0.15853]
 [ 0.61097 -0.88834 -1.05945]
 [-0.07531  0.10949  0.13058]]

Xii_3,1
[[ 0.50959 -0.74094 -0.88366]
 [ 3.4055  -4.95154 -5.90528]
 [-0.41975  0.61031  0.72786]]

Xii_3,2
[[-0.21694  0.31543  0.37619]
 [-1.44977  2.10794  2.51397]
 [ 0.17869 -0.25982 -0.30986]]


In [5]:
"""
P1.I.b.iii
--------
Calculate the full reconstruction.
"""
# The full reconstruction would be the aggregation of the results from 
# P1.b.i & P1.b.ii. Thus the full reconstruction is given by:
Xcp = Xi + Xii

# Print dimensionality and slices of resulting tensor. 
print("Dimensionality of Xcp: {}".format(Xpc.shape))

print("")
print("Xcp_1,1")
print(Xcp[:,:,0,0])

print("\nXcp_1,2")
print(Xcp[:,:,0,1])

print("\nXcp_2,1")
print(Xcp[:,:,1,0])

print("\nXcp_2,2")
print(Xcp[:,:,1,1])

print("\nXcp_3,1")
print(Xcp[:,:,2,0])

print("\nXcp_3,2")
print(Xcp[:,:,2,1])


Dimensionality of Xcp: (3, 3, 3, 2)

Xcp_1,1
[[4.65282 6.20662 5.85418]
 [3.73957 7.911   7.84191]
 [4.98758 5.71081 5.26395]]

Xcp_1,2
[[4.34319 5.11792 4.73941]
 [4.91554 4.61758 4.10311]
 [4.19626 5.32356 4.98562]]

Xcp_2,1
[[4.03306 5.52476 5.22988]
 [2.93594 7.45051 7.48712]
 [4.42173 4.95166 4.54735]]

Xcp_2,2
[[3.8353  4.46119 4.12268]
 [4.46351 3.83913 3.34603]
 [3.66595 4.7004  4.40881]]

Xcp_3,1
[[6.25937 6.31464 5.69137]
 [9.32218 2.30883 0.86059]
 [5.32601 7.66095 7.29829]]

Xcp_3,2
[[4.85071 6.53397 6.17118]
 [3.76498 8.50698 8.47717]
 [5.2428  5.95438 5.48109]]


In [6]:
"""
P1.II
--------
Compute the reconstruction of the Tucker decomposition.
"""
from tensorly import tucker_tensor

G11 = np.asarray([38.946, 0.8653, .9666, -4.8832]).reshape(2, 2)

G21 = np.asarray([-0.4799, -0.0792, -1.7302, -4.3675]).reshape(2, 2)

G12 = np.asarray([0.7059, -1.6496, 0.7553, -1.1648]).reshape(2, 2)

G22 = np.asarray([5.7493, -3.3204, -2.0019, 7.6587 ]).reshape(2, 2)

U1 = np.asarray([0.5661, -0.1945, 0.6005, -0.5685, 0.5648, 0.7994]).reshape(3, 2)

U2 = np.asarray([0.5031, 0.8331, 0.6345, -0.1755, 0.5867, -0.5246]).reshape(3, 2)

U3 = np.asarray([0.5773, -0.3364, 0.5013, -0.5733, 0.6445, 0.7471]).reshape(3, 2)

U4 = np.asarray([0.7524, -0.6587, 0.6587, 0.7524]).reshape(2, 2)

# Bind reference to core tensor G.
G = np.asarray([G11, G21, G12, G22]).reshape(2, 2, 2, 2)

Xtucker = tucker_tensor.tucker_to_tensor((G, [U1, U2, U3, U4]))

print("Shape of reconstructed tensor: {}".format(Xtucker.shape))

print("")
print("Xtucker_1,1")
print(Xtucker[:,:,0,0])

print("\nXtucker_1,2")
print(Xtucker[:,:,0,1])

print("\nXtucker_2,1")
print(Xtucker[:,:,1,0])

print("\nXtucker_2,2")
print(Xtucker[:,:,1,1])

print("\nXtucker_3,1")
print(Xtucker[:,:,2,0])

print("\nXtucker_3,2")
print(Xtucker[:,:,2,1])


Shape of reconstructed tensor: (3, 3, 3, 2)

Xtucker_1,1
[[2.99861 5.69567 5.83211]
 [1.29308 6.30948 7.21663]
 [8.16975 4.9483  2.99313]]

Xtucker_1,2
[[5.3689  5.70916 4.96526]
 [5.98013 6.08205 5.19245]
 [4.57487 5.62486 5.1583 ]]

Xtucker_2,1
[[ 1.81741  4.70075  5.05835]
 [-0.19876  5.42224  6.69002]
 [ 7.64646  3.49445  1.41422]]

Xtucker_2,2
[[5.68431 5.08491 4.08604]
 [6.6348  5.31253 4.00956]
 [4.01155 5.29641 4.96748]]

Xtucker_3,1
[[6.4876  7.33725 6.53488]
 [6.72026 7.26994 6.36605]
 [6.9159  8.72803 8.07223]]

Xtucker_3,2
[[1.91262 5.86532 6.44382]
 [0.91922 6.66557 7.79044]
 [4.95192 4.63444 3.80933]]


In [14]:
"""
P1.III
--------
Calculate the MSE for both the CP and Tucker decompositions. Briefly discuss 
(2-3 sentences should be sufficient) the difference, especially regarding the 
relative reduction of features for each method.
"""
X11 = np.asarray([4., 0., 9., 7., 9., 9., 4., 8., 5.,]).reshape(3, 3)

X21 = np.asarray([7., 8., 2., 1., 5., 8., 7., 9., 2.,]).reshape(3, 3)

X31 = np.asarray([7., 9., 4., 10., 1., 2., 1., 5., 8.,]).reshape(3, 3)

X12 = np.asarray([6., 5., 1., 3., 3., 5., 1., 8., 7.,]).reshape(3, 3)

X22 = np.asarray([8., 2., 3., 4., 3., 3., 2., 4., 6.,]).reshape(3, 3)

X32 = np.asarray([6., 6., 8., 5., 9., 8., 3., 9., 5.,]).reshape(3, 3)


# Populate Xactual with provided frontal slices.
Xactual = np.zeros(3 * 3 * 3 * 2).reshape(3, 3, 3, 2)
Xactual[:, :, 0, 0] = X11
Xactual[:, :, 1, 0] = X21
Xactual[:, :, 2, 0] = X31
Xactual[:, :, 0, 1] = X12
Xactual[:, :, 1, 1] = X22
Xactual[:, :, 2, 1] = X32


# Compute MSE of Xcp.
MSEcp = np.power((Xactual - Xcp).ravel(), 2).sum() / Xactual.size
MSEtuc
ker = np.power((Xactual - Xtucker).ravel(), 2).sum() / Xactual.size

print("MSE CP    : {:.2f}".format(MSEcp))
print("MSE Tucker: {:.2f}".format(MSEtucker))


1

In [15]:
Xactual.size

54

(54,)

In [ ]:
# Compute outer product of two vectors:

# U1[:,0].reshape(3, 1) *  U2[:,0].reshape(1, 3)

# np.outer(U1[:,0], U2[:,0])


# 𝜆1𝑈1,1 ∘ 𝑈2,1 ∘ 𝑈3,1 ∘ 𝑈4,1



# NumPy ufuncs, such as multiply, have an outer method that almost does what you want. The following:
temp = numpy.multiply.outer(A, B)
C = numpy.swapaxes(temp, 1, 2)

# produces a result such that temp[a, b, c, d] == A[a, b] * B[c, d]. 
# You want C[a, b, c, d] == A[a, c] * B[b, d]. The swapaxes call 
# rearranges temp to put it in the order you want.

einsum does not allow broadcasting by default


Whenever a label is repeated it is summed, so np.einsum('i,i', a, b) is equivalent to np.inner(a,b).


If a label appears only once, it is not summed, so np.einsum('i', a) produces a view of a with no changes.


np.einsum('ij,jk', a, b) describes traditional matrix multiplication and is equivalent to np.matmul(a,b).


Repeated subscript labels in one operand take the diagonal. For example, np.einsum('ii', a) is equivalent to np.trace(a).


np.einsum('ij', a) doesn’t affect a 2D array, while np.einsum('ji', a) takes its transpose


np.einsum('ij,jk', a, b) returns a matrix multiplication, while, np.einsum('ij,jh', a, b) returns the transpose of the multiplication since subscript ‘h’ precedes subscript ‘i’.


np.einsum('i->', a) is like np.sum(a, axis=-1), and np.einsum('ii->i', a) is like np.diag(a).


np.einsum('ij,jh->ih', a, b) directly specifies the order of the output subscript labels and therefore returns matrix multiplication, unlike the example above in implicit mode.

In [ ]:
import numpy as np 

d = 10 
U = np.random.rand(d) 
V = np.random.rand(d) 
T = np.random.rand(d) 
R = np.einsum('ai,aj,ak->ijk',U,V,T)

R


In [ ]:
U1[:,0].reshape(3, 1)

In [ ]:
U1[:,0].reshape(3, 1) *  U2[:,0].reshape(1, 3)


In [ ]:
np.outer(U1[:,0], U2[:,0])


In [ ]:
If G is of shape (2,2,2,2), then G o U_1 is of shape (3,2,2,2).

then G o U_1 o U_2 is of shape (3,3,2,2)

then G o U_1 o U_2 o U_3 is of shape (3,3,3,2)

and lastly G o U_1 o U_2 o U_3 o U_4 is of shape (3,3,3,2) which is the reconstruction matrix

Is my understanding correct?

# Q1

U_1,1 corresponds to the first U matrix (U_1) and the first column of that matrix?

In our example, that would be [.5719, .5885, .5715]?

Then, in part three, we have entire matrices denoted by X_1,1 which to me would be an individual element of a matrix (1=the row, and 1=the column).



In [ ]:
import numpy as np
from scipy.spatial import distance
from numpy import linalg as LA

prng = np.random.RandomState(516)

a = prng.randn(25).reshape(5, -1)
n0 = LA.norm(a[:,0])
n1 = distance.euclidean(a[:,0], np.zeros(a.shape[0]))

print("n0: {}".format(n0))
print("n1: {}".format(n1))


In [ ]:
a = [1, 2, 3]
b = [5, 6, 7, 8]
c = np.outer(b, a)

c